# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetbundles', '0003_auto_20160913_1135'),
        ('clients', '0002_auto_20160913_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsageBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_fee', models.FloatField(help_text='Monthly subscription fee')),
                ('service_charge', models.FloatField(help_text='Service/other charge')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client information'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(help_text='Customer first name example : Porimol', max_length=20),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(help_text='Customer last name example : Chandro', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mobile_number',
            field=models.CharField(help_text='Example : 01700000000', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nid_number',
            field=models.CharField(help_text="Customer national ID card's number.", max_length=60, null=True, verbose_name='NID Number'),
        ),
        migrations.AddField(
            model_name='clientusagebundle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name="Client's Name"),
        ),
        migrations.AddField(
            model_name='clientusagebundle',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetbundles.SpeedBundles', verbose_name='Speed Bundle'),
        ),
    ]
