# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetBundles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=100)),
                ('bundle_speed', models.CharField(max_length=15)),
                ('bundle_price', models.FloatField()),
                ('bundle_vat', models.FloatField()),
            ],
        ),
    ]
