# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetbundles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternetBundles',
            new_name='SpeedBundles',
        ),
    ]
