# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetbundles', '0002_auto_20160913_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedbundles',
            name='bundle_name',
            field=models.CharField(help_text='Internet package/bundle name. Example : Enterprise', max_length=100),
        ),
        migrations.AlterField(
            model_name='speedbundles',
            name='bundle_speed',
            field=models.CharField(help_text='Internet package/bundle speed(Bandwidth). Example : 2mbps', max_length=15),
        ),
        migrations.AlterField(
            model_name='speedbundles',
            name='bundle_vat',
            field=models.FloatField(help_text='It will convert into percentage(%)'),
        ),
    ]
